sonar.projectKey=fikua_fikua-starflux
sonar.organization=fikua

sonar.projectName=fikua-starflux

# Path is relative to the sonar-project.properties file.
sonar.sources=.
sonar.exclusions=**/*_test.go

sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out

sonar.sourceEncoding=UTF-8
